-- CMS-Servisi Veritabanı Şeması v4.3

CREATE TABLE `sayfalar` (
  `sayfa_id` INT AUTO_INCREMENT PRIMARY KEY,
  `baslik` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL UNIQUE,
  `icerik` TEXT,
  `olusturma_tarihi` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `bannerlar` (
  `banner_id` INT AUTO_INCREMENT PRIMARY KEY,
  `banner_adi` VARCHAR(255) NOT NULL,
  `resim_url` VARCHAR(255) NOT NULL,
  `hedef_url` VARCHAR(255) DEFAULT NULL,
  `aktif` BOOLEAN NOT NULL DEFAULT TRUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
